development:
  adapter: postgresql
  encoding: utf8
  database: finna_be_local_dev
  host: localhost
  username: admin
  password: 123123
  port: 5423

test: &test
  adapter: postgresql
  encoding: utf8
  database: finna_be_local_test
  host: localhost
  username: admin
  password: 123123
  port: 5423

cucumber:
  <<: *test